### ISSUE TITLE
[API/Settings] Remote control to edit a profile

### ISSUE THREAD

**Issue by christophermh44** [one-click-studio/gabin#30]
Inside a studio where hosts may move at different places, is there any possibility to easily change the shot associated to a mic source without having to edit a profile?

It may be interesting to control this kind of assignations, so it can be controlled by remote devices like Companion or custom Raspberry Pi devices.

**Comment by tillderoquefeuil** [comment]
Hello ! 👋 

In the next release, some controls will be added through OSC :
- power on/off
- set/edit a profile config
- change profile

On the other hand changing the shots associated with a mic is not planned for now, sorry 😢
