### ISSUE TITLE
[BUG] serveur tcp

### ISSUE THREAD

**Issue by LeGitHubDeTai** [one-click-studio/gabin#35]
salut, je voulais voir ce que c'est http://127.0.0.1:6481/ et j'ai eu cette erreur ;)

vous devez regarder si c'est bien du json avant de le parse.
c'est dans ce fichier: https://github.com/one-click-studio/gabin/blob/main/src/main/servers/TcpServer.ts

```
socket.on('data', (data: Buffer) => {
  const request: TcpRequest = JSON.parse(data.toString()) //ici
  if (!request.type){
     this.logger.error('received request without type', request)
     return
 }
 this.logger.debug('received request', request)
 this.sendRequestToClients(request)
});
```

![image](https://user-images.githubusercontent.com/65470169/222416955-123e5e6c-3faf-437c-8715-44f04ae2ce9c.png)

**Comment by tillderoquefeuil** [comment]
Removed TCP dependency
