### ISSUE TITLE
Documentation protocole OSC

### ISSUE THREAD

**Issue by christophermh44** [one-click-studio/gabin#46]
Bonjour,

Je vois que la version 0.3 de Gabin sera en mesure de se connecter à un serveur OSC.
J'envisage de développer un genre de middleware entre OBS et Gabin, qui communiquerait en OSC, pour répondre à 2 problématiques :
- Pouvoir changer les assignations de l'activité audio aux différents plans de caméras ( → si quelqu'un change de place en cours de live)
- Pouvoir déclencher un changement de plan (qui serait demandé par Gabin) dans OBS, après que la caméra concernée (PTZ) a fini de se réorienter.

Ma question : est-ce que l'API pour que Gabin puisse se brancher en OSC est / sera documentée quelque part ?

Merci :)

**Comment by tillderoquefeuil** [comment]
Ok parfait, je close du coup ;)
