### ISSUE TITLE
Impossible de sélectionner une source quand il y a plusieurs conteneurs ?

### ISSUE THREAD

**Issue by christophermh44** [one-click-studio/gabin#47]
Bonjour,

![image](https://github.com/one-click-studio/gabin/assets/2647313/abc7a400-10f3-44dc-8472-8169798d0739)

Dans cette configuration, le conteneur 1 fonctionne aussi bien en autocam qu'en manuel. Mais il ne se passe absolument rien dans le conteneur 2 (ni en autocam, ni en manuel).

Ce bug semble présent dans la v0.1 et dans la v0.2.

**Comment by tillderoquefeuil** [comment]
Je ne suis pas sûr de comprendre le problème, peux-tu me donner plus de détails? (ta config Gabin et OBS)

Et surtout, tu peux déjà tester avec la version en pre-release, j'ai corrigé pas mal de choses

**Comment by christophermh44** [comment]
J'ai voulu tester avec la pre-release et elle a crashé, voir ici : https://github.com/one-click-studio/gabin/issues/50

Concernant les détails demandés :

La configuration était établie comme suit :
- Connexion ASIO à ReaRoute (Reaper)
- 4 canaux ASIO utilisés en entrée
- Dans OBS, 2 conteneurs avec chacun d'entre eux les 3 mêmes caméras
- Dans OBS, 2 scènes, la première avec 1 seul conteneur, la deuxième avec 2 conteneurs
- Le reste des réglages (durée des scènes, affectations des caméras…) dans Gabin sont les réglages par défaut

Et le bug rencontré dans la v1 était le suivant :
- Gabin est bien en mesure de changer les scènes du premier conteneur
- Mais il ne parvient pas à faire de changements sur le deuxième conteneur (les boutons restent gris, même quand on clique dessus), et rien ne se passe dans OBS non plus

**Comment by christophermh44** [comment]
Précision utile :

J'ai essayé d'ajouter d'autres caméras dans mon deuxième conteneur, et le problème ne se produit plus. 
Je crois que je n'avais pas saisi qu'il fallait obligatoirement avoir des caméras différentes dans les conteneurs.

Toutefois, même s'il y a bien 2 caméras d'affichées :

![image](https://github.com/one-click-studio/gabin/assets/2647313/371f6f24-b9b7-4b77-8c1d-767bfa117ce7)

il n'y a qu'un seul bouton en bleu dans Gabin :

![image](https://github.com/one-click-studio/gabin/assets/2647313/ba434419-ff23-4914-9b73-4a937c4e0946)

Est-ce voulu ?

**Comment by tillderoquefeuil** [comment]
Ok merci, je suis en train de bosser dessus. Il y a effectivement des problèmes, j'ai refait la gestion en front des buttons, ça devrait être plus clair maintenant.

J'ai un dernier problème de logique dans le back, il arrive que la même source soit montrée en même temps sur deux containers.

En revanche, Gabin a une logique qui est : un container actif, tous les autres en plans d'illustrations.
Si tu cliques sur un plan, celui-ci devient instantanément le container actif. Je ne sais pas trop comment ça va se comporter, cette logique à vraiment été pensée pour une scène mono-container.

Je fixe le problème de double sources affichées lundi, et pour le reste ce n'est pas la prio pour le moment!

**Comment by christophermh44** [comment]
C'est bon à savoir, merci !

**Comment by tillderoquefeuil** [comment]
Tout est fix et poussé sur pre-release!
