### ISSUE TITLE
CPU à 100% ?

### ISSUE THREAD

**Issue by christophermh44** [one-click-studio/gabin#52]
Dans le cadre des tests et tentatives (multiples) de corrections sur le ticket #50, je me suis rendu compte que Gabin utilisait tout le CPU, même avec une bonne conf de PC.
Ci-dessous, en A, je démarre l'autocam de Gabin, en B, je le stoppe :

![image](https://github.com/one-click-studio/gabin/assets/2647313/062cd668-ec58-4a80-bc02-0323dfd6f950)

Est-ce normal (alors que j'ai quand même une bonne conf de PC ^^) ?

De mon côté, sur la solution que j'utilisais jusqu'alors, la détection d'activité vocale était faite avec le plugin "ReaGate" de Reaper. Ce plugin qui est un simple gate a l'énorme avantage de jouer une note MIDI au choix, sur le canal de notre choix. Cette note reste active tant que le gate est "ouvert". Ce fonctionnement était nettement moins gourmand en ressources.

Si j'y parviens, j'ajouterai la possibilité d'utiliser cette détection d'activité via MIDI et je ferai une PR :)

**Comment by christophermh44** [comment]
**UPDATE** - La détection d'activité vocale via MIDI est prête à être pushée :) 
Mais je ne parviens pas à pousser de branche sur le dépôt, donc pas possible de faire une PR non plus. Si besoin pour traiter ce cas un peu à part, j'ouvre un autre ticket.

**Comment by christophermh44** [comment]
**UPDATE** - La détection d'activité vocale via MIDI a été testée en live et approuvée :)

**Comment by tillderoquefeuil** [comment]
Hello ! Désolé pour la latence !
Ok super, on va se pencher là-dessus mais pour l'instant il faut que je règle ce problème de CPU à 100%, ce n'est pas normal


(pour la PR, qu'est-ce qui bloque?)

**Comment by christophermh44** [comment]
Aucun problème :) 
Je revérifierai chez moi ce soir, mais je crois que je ne parvenais pas à pusher une branche sur le dépôt.

**Comment by christophermh44** [comment]
Je confirme, je n'ai pas les droits de push une branche sur le dépôt, pour pouvoir faire une pull request derrière.
![image](https://github.com/one-click-studio/gabin/assets/2647313/3cc3dc8c-594c-480f-80ec-b3d8e35ddd46)

Ou alors j'ai oublié de configurer un truc dans GitHub de mon côté ? 🤔
